/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package profinal;

/**
 *
 * @author aalvarado
 */
public class Menu extends javax.swing.JFrame {
    Persona Per [] = new Persona [15];
    Usuario Usu [] = new Usuario [15];
    Libro Lib [] = new Libro [15];
    Autor Aut [] = new Autor [15];
    int contador = 0;
    //int contador2 = 0;
    //int contador3 = 0;
    

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    
    public void limpiarCampos(){
        this.txtNombre.setText(""); this.txtIdentidad.setText(""); this.txtEdad.setText(""); this.txtFechaNacimiento.setText("");
        this.txtLugarNacimiento.setText(""); this.txtDireccion.setText(""); this.txtNacionalidad.setText("");
        this.txtIdUsuario.setText(""); this.txtUsuario.setText(""); this.txtContrasena.setText("");
        this.txtIdLibro.setText(""); this.txtTituloLibro.setText(""); this.txtEditorial.setText("");
        this.txtAnioPublicacion.setText(""); this.txtPais.setText(""); this.txtNumPaginas.setText("");
        this.txtGeneroLiterario.setText("");
        this.txtNombreAutor.setText(""); this.txtFechaNaciAutor.setText(""); this.txtLugarNaciAutor.setText("");
        this.txtNacionalidadAutor.setText(""); this.txtIdAutor.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forRegisUsuario = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIdentidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtLugarNacimiento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        txtNacionalidad = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtIdUsuario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        btnRegistar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnFicha = new javax.swing.JButton();
        forFicha = new javax.swing.JFrame();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDatos = new javax.swing.JTextArea();
        btnCerrar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDatos2 = new javax.swing.JTextArea();
        forRegisLibros = new javax.swing.JFrame();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtIdLibro = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTituloLibro = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtEditorial = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtAnioPublicacion = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtNumPaginas = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtGeneroLiterario = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar2 = new javax.swing.JButton();
        btnFichaLibro = new javax.swing.JButton();
        forFichaLibro = new javax.swing.JFrame();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtFichaLibro = new javax.swing.JTextArea();
        btnCerrar2 = new javax.swing.JButton();
        forRegisAutor = new javax.swing.JFrame();
        jLabel25 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        txtNombreAutor = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtFechaNaciAutor = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtLugarNaciAutor = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtNacionalidadAutor = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        txtIdAutor = new javax.swing.JTextField();
        btnGuardarAutor = new javax.swing.JButton();
        btnCancelarAutor = new javax.swing.JButton();
        btnFichaAutor = new javax.swing.JButton();
        forFichaAutor = new javax.swing.JFrame();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtFichaAutor = new javax.swing.JTextArea();
        btnCerrar3 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtFichaAutor2 = new javax.swing.JTextArea();
        forControlLibros = new javax.swing.JFrame();
        jLabel32 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtControlLibro = new javax.swing.JTextArea();
        btnCerrarControl = new javax.swing.JButton();
        forPrestamo = new javax.swing.JFrame();
        jLabel33 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        txtIdPrestamo = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtIdLibroP = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtFechaActual = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtFechaDevolucion = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        btnGuardarPresta = new javax.swing.JButton();
        btnCancelarPresta = new javax.swing.JButton();
        btnNotificacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegisUsuario = new javax.swing.JButton();
        btnRegisLibro = new javax.swing.JButton();
        btnRegisAutor = new javax.swing.JButton();
        btnControl = new javax.swing.JButton();
        btnControlPrestamos = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();

        forRegisUsuario.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        forRegisUsuario.setTitle("Registro de nuevos usuarios");

        jLabel4.setFont(new java.awt.Font("Capture it", 0, 18)); // NOI18N
        jLabel4.setText("Registro de nuevos usuarios");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Personales", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Nombre Completo:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Identidad:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Edad:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Fecha de nacimiento:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Lugar de nacimiento:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Dirección:");

        txtDireccion.setColumns(20);
        txtDireccion.setRows(5);
        jScrollPane1.setViewportView(txtDireccion);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Nacionalidad:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaNacimiento)
                    .addComponent(txtLugarNacimiento)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(txtNacionalidad, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIdentidad)
                    .addComponent(txtEdad)
                    .addComponent(txtNombre))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtLugarNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de Acceso", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("ID Usuario:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Usuario:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Contraseña:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(169, 169, 169)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtIdUsuario)
                    .addComponent(txtUsuario)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRegistar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegistar.setText("Registrar");
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnFicha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFicha.setText("Ver Ficha");
        btnFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFichaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout forRegisUsuarioLayout = new javax.swing.GroupLayout(forRegisUsuario.getContentPane());
        forRegisUsuario.getContentPane().setLayout(forRegisUsuarioLayout);
        forRegisUsuarioLayout.setHorizontalGroup(
            forRegisUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forRegisUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(134, 134, 134))
            .addGroup(forRegisUsuarioLayout.createSequentialGroup()
                .addGroup(forRegisUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forRegisUsuarioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(forRegisUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(forRegisUsuarioLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnFicha)
                        .addGap(195, 195, 195)
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistar)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        forRegisUsuarioLayout.setVerticalGroup(
            forRegisUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forRegisUsuarioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(forRegisUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistar)
                    .addComponent(btnCancelar)
                    .addComponent(btnFicha))
                .addGap(22, 22, 22))
        );

        forFicha.setTitle("Ficha de Usuario");

        jLabel15.setFont(new java.awt.Font("Capture it", 0, 18)); // NOI18N
        jLabel15.setText("Ficha de Usuario");

        txtDatos.setColumns(20);
        txtDatos.setRows(5);
        jScrollPane2.setViewportView(txtDatos);

        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        txtDatos2.setColumns(20);
        txtDatos2.setRows(5);
        jScrollPane5.setViewportView(txtDatos2);

        javax.swing.GroupLayout forFichaLayout = new javax.swing.GroupLayout(forFicha.getContentPane());
        forFicha.getContentPane().setLayout(forFichaLayout);
        forFichaLayout.setHorizontalGroup(
            forFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forFichaLayout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addComponent(btnCerrar)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forFichaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(forFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forFichaLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forFichaLayout.createSequentialGroup()
                        .addGroup(forFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                            .addComponent(jScrollPane5))
                        .addGap(37, 37, 37))))
        );
        forFichaLayout.setVerticalGroup(
            forFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forFichaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel15)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(24, 24, 24))
        );

        forRegisLibros.setTitle("Registar Libros");

        jLabel16.setFont(new java.awt.Font("Capture it", 0, 18)); // NOI18N
        jLabel16.setText("Registro de Nuevos Libros");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Libros", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("ID Libro:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Titulo del Libro:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Editorial:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Año de Publicación:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Pais:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("N° de Paginas:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Genero Literario:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtEditorial, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTituloLibro, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdLibro, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAnioPublicacion)
                    .addComponent(txtPais)
                    .addComponent(txtNumPaginas)
                    .addComponent(txtGeneroLiterario, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtIdLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtTituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtAnioPublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtNumPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtGeneroLiterario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelar2.setText("Cancelar");
        btnCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar2ActionPerformed(evt);
            }
        });

        btnFichaLibro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFichaLibro.setText("Ver Ficha");
        btnFichaLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFichaLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout forRegisLibrosLayout = new javax.swing.GroupLayout(forRegisLibros.getContentPane());
        forRegisLibros.getContentPane().setLayout(forRegisLibrosLayout);
        forRegisLibrosLayout.setHorizontalGroup(
            forRegisLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forRegisLibrosLayout.createSequentialGroup()
                .addGroup(forRegisLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forRegisLibrosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(forRegisLibrosLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel16)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forRegisLibrosLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnFichaLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar2)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addGap(33, 33, 33))
        );
        forRegisLibrosLayout.setVerticalGroup(
            forRegisLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forRegisLibrosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(forRegisLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar2)
                    .addComponent(btnFichaLibro))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        forFichaLibro.setTitle("Ficha de Libro");

        jLabel24.setFont(new java.awt.Font("Capture it", 0, 18)); // NOI18N
        jLabel24.setText("Ficha de Libro");

        txtFichaLibro.setColumns(20);
        txtFichaLibro.setRows(5);
        jScrollPane3.setViewportView(txtFichaLibro);

        btnCerrar2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCerrar2.setText("Cerrar");
        btnCerrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout forFichaLibroLayout = new javax.swing.GroupLayout(forFichaLibro.getContentPane());
        forFichaLibro.getContentPane().setLayout(forFichaLibroLayout);
        forFichaLibroLayout.setHorizontalGroup(
            forFichaLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forFichaLibroLayout.createSequentialGroup()
                .addGroup(forFichaLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCerrar2)
                    .addGroup(forFichaLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(forFichaLibroLayout.createSequentialGroup()
                            .addGap(145, 145, 145)
                            .addComponent(jLabel24))
                        .addGroup(forFichaLibroLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        forFichaLibroLayout.setVerticalGroup(
            forFichaLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forFichaLibroLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel24)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnCerrar2)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        forRegisAutor.setTitle("Registar Autor");

        jLabel25.setFont(new java.awt.Font("Capture it", 0, 18)); // NOI18N
        jLabel25.setText("Registro de Autores");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de autor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Nombre Completo:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Fecha de nacimiento:");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("Lugar de nacimiento:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Nacionalidad:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreAutor)
                    .addComponent(txtFechaNaciAutor)
                    .addComponent(txtLugarNaciAutor)
                    .addComponent(txtNacionalidadAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtNombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtFechaNaciAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtLugarNaciAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtNacionalidadAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Otros datos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("ID Autor:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(txtIdAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtIdAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnGuardarAutor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGuardarAutor.setText("Guardar");
        btnGuardarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAutorActionPerformed(evt);
            }
        });

        btnCancelarAutor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelarAutor.setText("Cancelar");
        btnCancelarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAutorActionPerformed(evt);
            }
        });

        btnFichaAutor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFichaAutor.setText("Ver Ficha");
        btnFichaAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFichaAutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout forRegisAutorLayout = new javax.swing.GroupLayout(forRegisAutor.getContentPane());
        forRegisAutor.getContentPane().setLayout(forRegisAutorLayout);
        forRegisAutorLayout.setHorizontalGroup(
            forRegisAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forRegisAutorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(forRegisAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forRegisAutorLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel25))
                    .addGroup(forRegisAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forRegisAutorLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnFichaAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarAutor)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarAutor)
                        .addGap(26, 26, 26)))
                .addGap(18, 18, 18))
        );
        forRegisAutorLayout.setVerticalGroup(
            forRegisAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forRegisAutorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel25)
                .addGap(33, 33, 33)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(forRegisAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarAutor)
                    .addComponent(btnCancelarAutor)
                    .addComponent(btnFichaAutor))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        forFichaAutor.setTitle("Ficha de Autor");

        jLabel31.setFont(new java.awt.Font("Capture it", 0, 18)); // NOI18N
        jLabel31.setText("Ficha de Autor");

        txtFichaAutor.setColumns(20);
        txtFichaAutor.setRows(5);
        jScrollPane4.setViewportView(txtFichaAutor);

        btnCerrar3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCerrar3.setText("Cerrar");
        btnCerrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar3ActionPerformed(evt);
            }
        });

        txtFichaAutor2.setColumns(20);
        txtFichaAutor2.setRows(5);
        jScrollPane6.setViewportView(txtFichaAutor2);

        javax.swing.GroupLayout forFichaAutorLayout = new javax.swing.GroupLayout(forFichaAutor.getContentPane());
        forFichaAutor.getContentPane().setLayout(forFichaAutorLayout);
        forFichaAutorLayout.setHorizontalGroup(
            forFichaAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forFichaAutorLayout.createSequentialGroup()
                .addGroup(forFichaAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCerrar3)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(forFichaAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(forFichaAutorLayout.createSequentialGroup()
                            .addGap(157, 157, 157)
                            .addComponent(jLabel31))
                        .addGroup(forFichaAutorLayout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        forFichaAutorLayout.setVerticalGroup(
            forFichaAutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forFichaAutorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel31)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrar3)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel32.setFont(new java.awt.Font("Capture it", 0, 18)); // NOI18N
        jLabel32.setText("Control de Libros");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Libro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N

        txtControlLibro.setColumns(20);
        txtControlLibro.setRows(5);
        jScrollPane7.setViewportView(txtControlLibro);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnCerrarControl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCerrarControl.setText("Cerrar");
        btnCerrarControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarControlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout forControlLibrosLayout = new javax.swing.GroupLayout(forControlLibros.getContentPane());
        forControlLibros.getContentPane().setLayout(forControlLibrosLayout);
        forControlLibrosLayout.setHorizontalGroup(
            forControlLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forControlLibrosLayout.createSequentialGroup()
                .addGroup(forControlLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCerrarControl)
                    .addGroup(forControlLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(forControlLibrosLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(forControlLibrosLayout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addComponent(jLabel32))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        forControlLibrosLayout.setVerticalGroup(
            forControlLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forControlLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarControl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel33.setFont(new java.awt.Font("Capture it", 0, 18)); // NOI18N
        jLabel33.setText("Ficha de Prestamo");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de prestamo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N

        jLabel34.setText("ID Prestamo:");

        jLabel35.setText("ID Libro:");

        jLabel36.setText("Fecha de Entrega:");

        jLabel37.setText("Fecha de Devolución:");

        jLabel38.setText("Observaciones:");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane8.setViewportView(txtObservaciones);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38))
                .addGap(77, 77, 77)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdPrestamo)
                    .addComponent(txtIdLibroP)
                    .addComponent(txtFechaActual)
                    .addComponent(txtFechaDevolucion)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtIdPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtIdLibroP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(txtFechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(txtFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardarPresta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGuardarPresta.setText("Guardar");

        btnCancelarPresta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelarPresta.setText("Cancelar");

        btnNotificacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNotificacion.setText("Enviar Notificacion");

        javax.swing.GroupLayout forPrestamoLayout = new javax.swing.GroupLayout(forPrestamo.getContentPane());
        forPrestamo.getContentPane().setLayout(forPrestamoLayout);
        forPrestamoLayout.setHorizontalGroup(
            forPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forPrestamoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(forPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forPrestamoLayout.createSequentialGroup()
                        .addComponent(btnNotificacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(btnCancelarPresta)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarPresta))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forPrestamoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addGap(131, 131, 131))
        );
        forPrestamoLayout.setVerticalGroup(
            forPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forPrestamoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(forPrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarPresta)
                    .addComponent(btnCancelarPresta)
                    .addComponent(btnNotificacion))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ficha de Biblioteca");
        setBackground(java.awt.Color.gray);
        setLocation(new java.awt.Point(0, 0));

        jLabel1.setFont(new java.awt.Font("Capture it", 0, 36)); // NOI18N
        jLabel1.setText("BIBLIOTECA - CAFE CON LIBROS");

        jLabel2.setFont(new java.awt.Font("Capture it", 0, 18)); // NOI18N
        jLabel2.setText("Proyecto Final - Grupo #3");

        jLabel3.setFont(new java.awt.Font("Capture it", 0, 24)); // NOI18N
        jLabel3.setText("Menu");

        btnRegisUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegisUsuario.setIcon(new javax.swing.ImageIcon("C:\\Users\\aalvarado\\Documents\\NetBeansProjects\\proFinal\\User.png")); // NOI18N
        btnRegisUsuario.setText("Registar Usuario");
        btnRegisUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisUsuarioActionPerformed(evt);
            }
        });

        btnRegisLibro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegisLibro.setIcon(new javax.swing.ImageIcon("C:\\Users\\aalvarado\\Documents\\NetBeansProjects\\proFinal\\Book.png")); // NOI18N
        btnRegisLibro.setText("Registar Libros");
        btnRegisLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisLibroActionPerformed(evt);
            }
        });

        btnRegisAutor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegisAutor.setIcon(new javax.swing.ImageIcon("C:\\Users\\aalvarado\\Documents\\NetBeansProjects\\proFinal\\Author.png")); // NOI18N
        btnRegisAutor.setText("Registar Autor");
        btnRegisAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisAutorActionPerformed(evt);
            }
        });

        btnControl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnControl.setIcon(new javax.swing.ImageIcon("C:\\Users\\aalvarado\\Documents\\NetBeansProjects\\proFinal\\Books.png")); // NOI18N
        btnControl.setText("Control de Libros");
        btnControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlActionPerformed(evt);
            }
        });

        btnControlPrestamos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnControlPrestamos.setIcon(new javax.swing.ImageIcon("C:\\Users\\aalvarado\\Documents\\NetBeansProjects\\proFinal\\Load.png")); // NOI18N
        btnControlPrestamos.setText("Control de Prestamos");
        btnControlPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControlPrestamosActionPerformed(evt);
            }
        });

        jLabel39.setIcon(new javax.swing.ImageIcon("C:\\Users\\aalvarado\\Documents\\NetBeansProjects\\proFinal\\Team.png")); // NOI18N

        jLabel40.setIcon(new javax.swing.ImageIcon("C:\\Users\\aalvarado\\Documents\\NetBeansProjects\\proFinal\\Library.png")); // NOI18N

        jLabel41.setIcon(new javax.swing.ImageIcon("C:\\Users\\aalvarado\\Documents\\NetBeansProjects\\proFinal\\Books-2.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel39)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel41)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegisUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegisLibro)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegisAutor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnControl)
                        .addGap(18, 18, 18)
                        .addComponent(btnControlPrestamos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(55, 55, 55)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                                .addComponent(jLabel39)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel3)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRegisUsuario)
                                    .addComponent(btnRegisLibro)
                                    .addComponent(btnRegisAutor))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnControl)
                                    .addComponent(btnControlPrestamos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(45, 45, 45))))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisUsuarioActionPerformed
        forRegisUsuario.setVisible(true);
        //forRegisUsuario.setLocationRelativeTo(null);
        forRegisUsuario.setLocation(200,15);
        forRegisUsuario.setSize(565, 742);
        forRegisUsuario.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }//GEN-LAST:event_btnRegisUsuarioActionPerformed

    private void btnRegisLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisLibroActionPerformed
        forRegisLibros.setVisible(true);
        //forRegisLibros.setLocationRelativeTo(null);
        forRegisLibros.setLocation(200, 25);
        forRegisLibros.setSize(530, 550);
        forRegisLibros.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }//GEN-LAST:event_btnRegisLibroActionPerformed

    private void btnRegisAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisAutorActionPerformed
        forRegisAutor.setVisible(true);
        //forRegisAutor.setLocationRelativeTo(null);
        forRegisAutor.setLocation(200, 25);
        forRegisAutor.setSize(570, 580);
        forRegisAutor.setDefaultCloseOperation(HIDE_ON_CLOSE);
        
    }//GEN-LAST:event_btnRegisAutorActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limpiarCampos();
        forRegisUsuario.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.limpiarCampos();
        forFicha.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFichaActionPerformed
        forFicha.setVisible(true);
        //forFicha.setLocationRelativeTo(null);
        forFicha.setLocation(750, 25);
        forFicha.setSize(500, 550);
        forFicha.setDefaultCloseOperation(HIDE_ON_CLOSE);
        txtDatos.setText(Per[contador].getInfoPersona());
        txtDatos2.setText(Usu[contador].getInfoUsuario());
    }//GEN-LAST:event_btnFichaActionPerformed

    private void btnFichaLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFichaLibroActionPerformed
        forFichaLibro.setVisible(true);
        //forFichaLibro.setLocationRelativeTo(null);
        forFichaLibro.setLocation(750, 25);
        forFichaLibro.setSize(460, 400);
        forFichaLibro.setDefaultCloseOperation(HIDE_ON_CLOSE);
        txtFichaLibro.setText(Lib[contador].getInfoLibro());
    }//GEN-LAST:event_btnFichaLibroActionPerformed

    private void btnFichaAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFichaAutorActionPerformed
        forFichaAutor.setVisible(true);
        //forFichaAutor.setLocationRelativeTo(null);
        forFichaAutor.setLocation(750, 25);
        forFichaAutor.setSize(460, 440);
        forFichaAutor.setDefaultCloseOperation(HIDE_ON_CLOSE);
        txtFichaAutor.setText(Aut[contador].getInfoAutor());
        txtFichaAutor2.setText(Per[contador].getInfoDatAutor());
    }//GEN-LAST:event_btnFichaAutorActionPerformed

    private void btnCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar2ActionPerformed
        this.limpiarCampos();
        forRegisLibros.setVisible(false);
    }//GEN-LAST:event_btnCancelar2ActionPerformed

    private void btnCancelarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAutorActionPerformed
        this.limpiarCampos();
        forRegisAutor.setVisible(false);
    }//GEN-LAST:event_btnCancelarAutorActionPerformed

    private void btnCerrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar2ActionPerformed
        this.limpiarCampos();
        forFichaLibro.setVisible(false);
    }//GEN-LAST:event_btnCerrar2ActionPerformed

    private void btnCerrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar3ActionPerformed
        this.limpiarCampos();
        forFichaAutor.setVisible(false);
    }//GEN-LAST:event_btnCerrar3ActionPerformed

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
        Per[contador] = new Persona();
        Usu[contador] = new Usuario();
        Per[contador].setNombreCompleto(txtNombre.getText());
        Per[contador].setIdentidad(Integer.parseInt(txtIdentidad.getText()));
        Per[contador].setEdad(Integer.parseInt(txtEdad.getText()));
        Per[contador].setFechaNacimiento(txtFechaNacimiento.getText());
        Per[contador].setLugarNacimiento(txtLugarNacimiento.getText());
        Per[contador].setDireccion(txtDireccion.getText());
        Per[contador].setNacionalidad(txtNacionalidad.getText());
        Usu[contador].setIdUsuario(Integer.parseInt(txtIdUsuario.getText()));
        Usu[contador].setNombreUsuario(txtUsuario.getText());
        Usu[contador].setContraseña(txtContrasena.getText());
        this.limpiarCampos();
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Lib[contador] = new Libro();
        Lib[contador].setIdLibro(Integer.parseInt(txtIdLibro.getText()));
        Lib[contador].setTituloLibro(txtTituloLibro.getText());
        Lib[contador].setEditorial(txtEditorial.getText());
        Lib[contador].setAñoPublicacion(Integer.parseInt(txtAnioPublicacion.getText()));
        Lib[contador].setPais(txtPais.getText());
        Lib[contador].setNumeroPaginas(Integer.parseInt(txtNumPaginas.getText()));
        Lib[contador].setGeneroLiterario(txtGeneroLiterario.getText());
        this.limpiarCampos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuardarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAutorActionPerformed
        Per[contador] = new Persona();
        Aut[contador] = new Autor();
        Aut[contador].setNombreAutor(txtNombreAutor.getText());
        Per[contador].setFechaNacimiento(txtFechaNaciAutor.getText());
        Per[contador].setLugarNacimiento(txtLugarNaciAutor.getText());
        Per[contador].setNacionalidad(txtNacionalidadAutor.getText());
        Aut[contador].setIdAutor(Integer.parseInt(txtIdAutor.getText()));
        this.limpiarCampos();
    }//GEN-LAST:event_btnGuardarAutorActionPerformed

    private void btnControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlActionPerformed
        forControlLibros.setVisible(true);
        //forFichaLibro.setLocationRelativeTo(null);
        forControlLibros.setLocation(300, 25);
        forControlLibros.setSize(460, 400);
        forControlLibros.setDefaultCloseOperation(HIDE_ON_CLOSE);
        txtControlLibro.setText(Lib[contador].getInfoLibro());
    }//GEN-LAST:event_btnControlActionPerformed

    private void btnCerrarControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarControlActionPerformed
        forControlLibros.setVisible(false);
    }//GEN-LAST:event_btnCerrarControlActionPerformed

    private void btnControlPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlPrestamosActionPerformed
        forPrestamo.setVisible(true);
        //forFichaLibro.setLocationRelativeTo(null);
        forPrestamo.setLocation(300, 25);
        forPrestamo.setSize(490, 510);
        forPrestamo.setDefaultCloseOperation(HIDE_ON_CLOSE);
        //forPrestamo.setText(Lib[contador].getInfoLibro());
    }//GEN-LAST:event_btnControlPrestamosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar2;
    private javax.swing.JButton btnCancelarAutor;
    private javax.swing.JButton btnCancelarPresta;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCerrar2;
    private javax.swing.JButton btnCerrar3;
    private javax.swing.JButton btnCerrarControl;
    private javax.swing.JButton btnControl;
    private javax.swing.JButton btnControlPrestamos;
    private javax.swing.JButton btnFicha;
    private javax.swing.JButton btnFichaAutor;
    private javax.swing.JButton btnFichaLibro;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarAutor;
    private javax.swing.JButton btnGuardarPresta;
    private javax.swing.JButton btnNotificacion;
    private javax.swing.JButton btnRegisAutor;
    private javax.swing.JButton btnRegisLibro;
    private javax.swing.JButton btnRegisUsuario;
    private javax.swing.JButton btnRegistar;
    private javax.swing.JFrame forControlLibros;
    private javax.swing.JFrame forFicha;
    private javax.swing.JFrame forFichaAutor;
    private javax.swing.JFrame forFichaLibro;
    private javax.swing.JFrame forPrestamo;
    private javax.swing.JFrame forRegisAutor;
    private javax.swing.JFrame forRegisLibros;
    private javax.swing.JFrame forRegisUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField txtAnioPublicacion;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextArea txtControlLibro;
    private javax.swing.JTextArea txtDatos;
    private javax.swing.JTextArea txtDatos2;
    private javax.swing.JTextArea txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtFechaActual;
    private javax.swing.JTextField txtFechaDevolucion;
    private javax.swing.JTextField txtFechaNaciAutor;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextArea txtFichaAutor;
    private javax.swing.JTextArea txtFichaAutor2;
    private javax.swing.JTextArea txtFichaLibro;
    private javax.swing.JTextField txtGeneroLiterario;
    private javax.swing.JTextField txtIdAutor;
    private javax.swing.JTextField txtIdLibro;
    private javax.swing.JTextField txtIdLibroP;
    private javax.swing.JTextField txtIdPrestamo;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtIdentidad;
    private javax.swing.JTextField txtLugarNaciAutor;
    private javax.swing.JTextField txtLugarNacimiento;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNacionalidadAutor;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreAutor;
    private javax.swing.JTextField txtNumPaginas;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtTituloLibro;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
